FROM ai-gpu-base:latest

ENV PATH="/venv/bin:$PATH"

RUN --mount=type=cache,target=/root/.cache/pip \
    pip install torch --index-url https://download.pytorch.org/whl/cu126 \
 && pip install git+https://github.com/salute-developers/GigaAM.git \
 && rm -rf /tmp/*

WORKDIR /app
COPY stt_server.py /app/
CMD ["python", "/app/stt_server.py"]

